fahbackup: accommodate bash -e

diff --git a/fahbackup b/fahbackup
--- a/fahbackup
+++ b/fahbackup
@@ -60,15 +60,17 @@ fi
 #Back up fah directory
 date=$(date +%Y-%m-%d-%H%M)
 echo backing up...
-tar -cf fahbackup-data/wip/$date.tar fah
-tar -tf fahbackup-data/wip/$date.tar > /dev/null
-RET=$?
-if [ $RET -ne 0 ]; then
+#
+# tar may return non-zero exit code if a file is changed mid-run;
+# to accommodate this scenario we test the archive for consistency post-creation
+# 
+tar -cf fahbackup-data/wip/$date.tar fah || true
+if ! tar -tf fahbackup-data/wip/$date.tar > /dev/null ; then
 	echo backup failed!
 	exit 1
 fi
 
-CURRENT=$(ls fahbackup-data/current 2> /dev/null)
+CURRENT=$(ls fahbackup-data/current 2> /dev/null || true)
 if [ -n "$CURRENT" ]; then
 	#
 	#Remove previous
